routes/web.php
<?php

use Illuminate\Support\Facades\Response;
use App\Comuna;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('/votaciones', 'VotacionController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('getcomuna','VotacionController@getComuna');

app/Candidato.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Candidato extends Model
{
    protected $table = 'candidatos';
    protected $fillable = ['nombre'];

}

app/Comuna.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comuna extends Model
{
    protected $table = 'comunas';
    protected $fillable = ['region_id','nombre'];

}

app/Contacto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contacto extends Model
{
    protected $table = 'contactos';
}

app/Medios.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Medios extends Model
{
    protected $table = 'medios';
    protected $fillable = ['user_id','nombre'];
}

app/Region.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    protected $table = 'regions';
    protected $fillable = ['nombre','ordinal'];

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email','alias',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Votacion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Votacion extends Model
{
    protected $table = 'votacions';
    protected $fillable = ['nombre','alias','rut','email','region','comuna','candidato_id','region_id'];
}

app/Http/Controllers/CandidatoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CandidatoController extends Controller
{
    //
}

app/Http/Controllers/ComunaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ComunaController extends Controller
{
    protected $table = 'comunas';

    public function regions()
	{
		 return $this->belongsTo('regions');
	}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MediosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MediosController extends Controller
{
    
}

app/Http/Controllers/RegionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class RegionController extends Controller
{
    protected $table = 'regions';

    public function comuna()
	{
		 return $this->hasMany('comuna');
	}
}

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use App\Candidato;
use App\Region;
use App\User;
use Illuminate\Http\Request;

class UsuarioController extends Controller
{
    public function index(){}
    public function create()
    {
       $regiones = Region::all();
       $candidatos = Candidato::all();
       return view('votaciones',['candidatos' => $candidatos]);
    }
    public function store(Request $request){
        $input = $request->all();
        $request->validate([
            'nombre' => 'required',
            'alias' => 'required|min:5|unique:users',
            'rut' => 'required|unique:users',
            'email' => 'required|string|email|max:255,regex:/(.*)@example\.com$/i'
        ]);
        User::create($input);
    }
    public function show(){}
    public function update(){}
    public function destroy(){}
}

app/Http/Controllers/VotacionController.php
<?php

namespace App\Http\Controllers;

use App\Candidato;
use App\Comuna;
use App\Medios;
use App\Region;
use App\Votacion;
use Illuminate\Http\Request;

class VotacionController extends Controller
{
    public function index(){}
    public function create()
    {
       $regiones = Region::all();
       $candidatos = Candidato::all();
       $comunas = Comuna::all();
       $data['regiones'] = Region::get(["nombre","id"]);
       return view('votaciones',['candidatos' => $candidatos,'regiones' => $regiones,'comunas' => $comunas,'data' => $data]);
    }
    public function store(Request $request){
        $input = $request->all();
        $checkboxs = $request->get('checkbox');
        $request->validate([
            'nombre' => 'required',
            'alias' => 'required|min:5|unique:votacions',
            'rut' => 'required|unique:votacions',
            'email' => 'required|string|email|max:255,regex:/(.*)@example\.com$/i'

        ]);
        Votacion::create($input);
        
        foreach($checkboxs as $key => $value)
        {
        Medios::create([
        'user_id' => auth()->id(),
        'nombre' => $value,
          ]);
        }     
        return redirect('home');
    }

    public function getRegion()
    {
        $data['regiones'] = Region::get(["nombre","id"]);
        return view('votaciones',$data);
    }
    public function getComuna(Request $request)
    {
        $data['comunas'] = Comuna::where("region_id",$request->get('region'))
                    ->get(["nombre","id"]);
        return response()->json($data);
    }

    public function show(){}
    public function update(){}
    public function destroy(){}
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <a href="{{ URL::route('votaciones.create') }}" class="btn btn-default">Votaciones</a>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/votaciones.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="{{asset('js/jquery.min.js')}}"></script>
        <script src="{{asset('js/app.js')}}"></script>
        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;600&display=swap" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ route('login') }}">Login</a>

                        @if (Route::has('register'))
                            <a href="{{ route('register') }}">Register</a>
                        @endif
                    @endauth
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Formulario de votación
                </div>

                <form method="post" action="{{ route('votaciones.store') }}">
                  <input type="hidden" name="user" value="{{Auth::id()}}"><br />

                    <div class="mb-3">
                        @csrf
                      <label class="form-label">Nombre y apellido</label>   <input type="text" class="form-control" id="nombre" name="nombre">
                    </div>
                    <div class="mb-3">
                      <label class="form-label">Alias</label>   <input type="text" class="form-control" id="alias" name="alias">
                    </div>
                      <div class="mb-3">
                      <label class="form-label">Rut</label>   <input type="text" class="form-control" id="rut" name="rut">
                    </div>
                      <div class="mb-3">
                      <label class="form-label">Email</label><input type="text" class="form-control" id="email" name="email">
                    </div>
                      <div class="mb-3">
                      <label class="form-label">Región</label>
                      <select class="form-select" id="region" name="region" id="region-dropdown">
                        @foreach($regiones as $region)
                        <option value="{{$region->id}}">{{$region->nombre}}</option>
                        @endforeach
                      </select>
                    </div>
                      <div class="mb-3">
                      <label class="form-label">Comuna</label>
                      <select class="form-select" id="comuna" name="comuna" id="comuna-dropdown">
                        @foreach($comunas as $comuna)
                        <option value="{{$comuna->id}}">{{$comuna->nombre}}</option>
                        @endforeach
                      </select>
                    </div>
                      <div class="mb-3">
                      <label class="form-label">Candidato</label>

                      <div class="mb-3">
                        <select class="form-select" id="candidato_id" name="candidato_id">
                            @foreach($candidatos as $candidato)
                            <option value="{{$candidato->id}}">{{$candidato->nombre}}</option>
                            @endforeach
                          </select>
                    </div>
                    </div>
                    <div class="mb-3">
                      <div id="msg"></div>

                        <label class="form-label">Como se enteró de Nosotros</label><div class="form-check">
                            <input class="form-check-input" type="checkbox" value="web" id="miElementoCheckbox" name="checkbox[]">
                            <label class="form-check-label" for="webCheck">
                              Web
                            </label>
                          </div>
                          <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="tv" id="miElementoCheckbox" name="checkbox[]">
                            <label class="form-check-label" for="tvCheck">
                              TV
                            </label>
                          </div>
                          <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="redessociales" id="miElementoCheckbox" name="checkbox[]">
                            <label class="form-check-label" for="redessocialesCheck">
                              Redes Sociales
                            </label>
                          </div>
                          <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="amigo" id="miElementoCheckbox" name="checkbox[]">
                            <label class="form-check-label" for="amigoCheck">
                              Amigo
                            </label>
                          </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Votar</button>
                  </form>
            </div>
        </div>
        <script type="text/javascript">
       
      </script>
    </body>
</html>